services:
  postgres:
    image: postgres:16
    container_name: superstore_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: superstore
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data:/data
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  pgdata: