create view cleansed.sales as
select row_id,
       order_id,
       order_date,
       ship_date,
       ship_mode,
       customer_id,
       customer_name,
       segment,
       city,
       state,
       country,
       postal_code,
       market,
       region,
       product_id,
       category,
       sub_category,
       product_name,
       sales,
       quantity,
       discount,
       profit,
       shipping_cost,
       order_priority,
       load_ts
from cleansed.sales_checked
where reject_reason is null;
